basepath = "."

locales = [
  "ar",
  "de",
  "es",
  "fr",
  "hi",
  "ja",
  "ru",
  "zh",
]
[env]

[[paths]]
  reference = "app/src/main/res/values/strings.xml"
  l10n = "app/src/main/res/values-{android_locale}/strings.xml"
