[[paths]]
  reference = "app/src/main/res/values/strings.xml"
  l10n = "app/src/main/res/values-{android_locale}/strings.xml"
  locales = [
        "de",
        "fr",
        "ar",
        "ja",
        "ru"
    ]
