basepath = "."

# Expose the following branches to localization
# Changes to this list should be announced to the l10n team ahead of time.
branches = [
    "main",
]

[env]

[[paths]]
  reference = "app/src/main/res/values/strings.xml"
